# Site
# -----------------------
url                 : ""
google_analytics_key: ""
google_site_verification: ""

# Serving
# -----------------------
port                : 4000
host                : 127.0.0.1
show_dir_listing    : false

# Language
# --------
# The primary language used in this project. You can set the language
# for each book individually below at 'defaults'.
# To understand what language tags to use, read:
# http://www.w3.org/International/articles/language-tags/
# For the registry of tags:
# http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
# Useful lookup tool: http://r12a.github.io/apps/subtags/
language            : en
locale              : fr
encoding            : UTF-8
timezone            : Etc/UTC

# Gem-based theme
# ---------------
# Are you importing a gem-based theme? By default we do not.
# If you are, remove the # before `theme:` and enter your theme's gem name.
# If you're using GitHub Pages, note that it may not support your theme.
# theme: your-theme-gem-name-here

# Custom-edition variable
# -----------------------
# Which edition are we creating? You can leave this as `default`.
# This can be used to create different editions of a book using
# Liquid control-flow tags, e.g. in includes, layouts and file-list
edition             : "default"

# Canonical URL
# -------------
# To make absolute links work, e.g. in canonical links in <head>,
# include the url where this site will live when it's live (production).
# E.g. canonical-url: "http://example.com"
# canonical-url: "http://example.com"

# Base URL
# --------
# If you're using GitHub Pages without a custom domain, make this
# the name of your repo, e.g. /jekyll-book-framework
# It must start with a slash. Otherwise you can leave it blank. See:
# http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/
baseurl             : ""

# Navigation
# ----------
# Show full navigation
show_full_navigation: false

# Default page variables
# ----------------------
plugins:
  - jekyll-sitemap
  - jekyll-scholar
  - jekyll-microtypo
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - materials
  - package.json
  - package-lock.json
  - node_modules
  - rsync-ignore.txt
  - env.json
  - env-model.json
  - gulpfile.js
  - assets/css/turetcss/

# Default page variables
# ----------------------
# Set default values here for all documents/pages in this publication.
# (For technical details, see http://jekyllrb.com/docs/configuration/#front-matter-defaults).
# Store only site configurations here, and book metadata (title, author, ISBNs) in _data/meta.yml
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# Jekyll Scholar
# ----------------
scholar:
  style             : american-political-science-association
  locale            : fr
  source            : _bibliography
  bibliography      : bibliography.bib
  relative          : "/6-appendices/bibliography/"
  sort_by           : author
  bibliography_list_tag : ul

# Jekyll Microtypo
# ----------------
microtypo:
  median: true

# HTML compression
# ----------------
# Configure HTML compression
# These settings control how your output HTML is compressed.
# See https://github.com/penibelst/jekyll-compress-html
compress_html:
  blanklines: true
